version: '3.9'

services:

    nginx:
        build:
            ./docker-container/nginx
        links:
            - php

    php:
        build: ./docker-container/php
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    postgres_master:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: MTS
            POSTGRES_PASSWORD: MTS
            POSTGRES_DB: MTS


